-- DB schema for Great Mega Forex (corrected)

CREATE TABLE IF NOT EXISTS admins (

  id INT AUTO_INCREMENT PRIMARY KEY,

  username VARCHAR(100) UNIQUE NOT NULL,

  password VARCHAR(255) NOT NULL,

  password_hash VARCHAR(255) DEFAULT NULL,

  created_at DATETIME DEFAULT CURRENT_TIMESTAMP

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS gallery (

  id INT AUTO_INCREMENT PRIMARY KEY,

  filename VARCHAR(255) NOT NULL,

  description TEXT,

  uploaded_at DATETIME DEFAULT CURRENT_TIMESTAMP

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS users (

  id INT AUTO_INCREMENT PRIMARY KEY,

  full_name VARCHAR(255),

  email VARCHAR(255) UNIQUE,

  password VARCHAR(255),

  created_at DATETIME DEFAULT CURRENT_TIMESTAMP

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;